export interface InstrumentData {
  instrument_id: number;
  isin: string | null;
  name: string;
  instrument_type: string;
  profile_name: string | null;
  risk_level_name: string | null;
  asset_class_level_name: string | null;
  market_cap_name: string | null;
  sector_name: string | null;
  sub_industry_name: string | null;
  country_exposure_name: string | null;
}

export const instruments: InstrumentData[] = [
  {
    instrument_id: 1,
    isin: null,
    name: "ABENGOA A",
    instrument_type: "Common Stock",
    profile_name: null,
    risk_level_name: null,
    asset_class_level_name: null,
    market_cap_name: null,
    sector_name: null,
    sub_industry_name: null,
    country_exposure_name: null,
  },
  {
    instrument_id: 2,
    isin: null,
    name: "ABENGOA B",
    instrument_type: "Common Stock",
    profile_name: null,
    risk_level_name: null,
    asset_class_level_name: null,
    market_cap_name: null,
    sector_name: null,
    sub_industry_name: null,
    country_exposure_name: null,
  },
  {
    instrument_id: 3,
    isin: "ES0132105018",
    name: "ACERINOX",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mid Cap",
    sector_name: "Materials",
    sub_industry_name: "Steel",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 4,
    isin: "US0079031078",
    name: "ADVANCED MICRO DEVICES INC",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Mega Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Semiconductors",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 5,
    isin: "ES0152768612",
    name: "AIRTIFICIAL INTELLIGENCE STRUCTURES",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Small Cap",
    sector_name: "Industrials",
    sub_industry_name: "Construction & Engineering",
    country_exposure_name: "Spain",
  },
  {
    instrument_id: 6,
    isin: "US02079K3059",
    name: "ALPHABET INC CL A",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Communication Services",
    sub_industry_name: "Interactive Media & Services",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 7,
    isin: "US02079K1079",
    name: "ALPHABET INC CL C",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Communication Services",
    sub_industry_name: "Interactive Media & Services",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 8,
    isin: "ES0109067019",
    name: "AMADEUS",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Large Cap",
    sector_name: "Industrials",
    sub_industry_name: "Data Processing & Outsourced Services",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 9,
    isin: "US0231351067",
    name: "AMAZON COM",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Consumer Discretionary",
    sub_industry_name: "Internet & Direct Marketing Retail",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 10,
    isin: "US0079031078",
    name: "AMD XETRA",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Mega Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Semiconductors",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 11,
    isin: "US02376R1023",
    name: "AMERICAN AIRLINES",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "High",
    asset_class_level_name: "Mature",
    market_cap_name: "Mid Cap",
    sector_name: "Industrials",
    sub_industry_name: "Airlines",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 12,
    isin: "ES0109260531",
    name: "AMPER",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Small Cap",
    sector_name: "Industrials",
    sub_industry_name: "Electrical Equipment",
    country_exposure_name: "Spain",
  },
  {
    instrument_id: 13,
    isin: "LU1681038243",
    name: "AMUNDI NASDAQ 100-EUR",
    instrument_type: "ETF",
    profile_name: "Hedging",
    risk_level_name: "Moderate",
    asset_class_level_name: "Growth",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Equity ETF",
    country_exposure_name: "US",
  },
  {
    instrument_id: 14,
    isin: "US0378331005",
    name: "APPLE INC",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Consumer Electronics",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 15,
    isin: "US03938L2034",
    name: "ARCELOR MITTAL CMN",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Large Cap",
    sector_name: "Materials",
    sub_industry_name: "Steel",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 16,
    isin: "LU1598757687",
    name: "ARCELORMITTAL",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Large Cap",
    sector_name: "Materials",
    sub_industry_name: "Steel",
    country_exposure_name: "Europe",
  },
  {
    instrument_id: 17,
    isin: "GB0000595859",
    name: "ARM HOLDINGS PLC - ADR",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Large Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Semiconductors",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 18,
    isin: "NL0010273215",
    name: "ASM LITHOGRAPHY HOLDING",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Semiconductor Equipment",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 19,
    isin: "USN070592100",
    name: "ASML ADR",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Semiconductor Equipment",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 20,
    isin: "US00206R1023",
    name: "AT&T RG",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Low",
    asset_class_level_name: "Mature",
    market_cap_name: "Large Cap",
    sector_name: "Communication Services",
    sub_industry_name: "Integrated Telecommunication Services",
    country_exposure_name: "US",
  },
  {
    instrument_id: 21,
    isin: "GB00BZ09BD16",
    name: "ATLASSIAN CORP PLC - CLASS A",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Large Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Application Software",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 22,
    isin: "ES0105216005",
    name: "AUDAX",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Small Cap",
    sector_name: "Utilities",
    sub_industry_name: "Renewable Electricity",
    country_exposure_name: "Europe",
  },
  {
    instrument_id: 23,
    isin: "US0605051046",
    name: "BANK OF AMERICA CORP",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "Mega Cap",
    sector_name: "Financials",
    sub_industry_name: "Diversified Banks",
    country_exposure_name: "US",
  },
  {
    instrument_id: 24,
    isin: "CA0679011084",
    name: "BARRICK GOLD CORP",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Large Cap",
    sector_name: "Materials",
    sub_industry_name: "Gold",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 25,
    isin: "AU000000BKY0",
    name: "BERKELEY",
    instrument_type: "ETC",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Small Cap",
    sector_name: "Commodities",
    sub_industry_name: "Uranium Exploration",
    country_exposure_name: "Spain",
  },
  {
    instrument_id: 26,
    isin: null,
    name: "BIOSEARCH",
    instrument_type: "Common Stock",
    profile_name: null,
    risk_level_name: null,
    asset_class_level_name: null,
    market_cap_name: null,
    sector_name: null,
    sub_industry_name: null,
    country_exposure_name: null,
  },
  {
    instrument_id: 27,
    isin: "US11135F1012",
    name: "BROADCOM INC",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Information Technology",
    sub_industry_name: null,
    country_exposure_name: "Global",
  },
  {
    instrument_id: 28,
    isin: "ES0140609019",
    name: "CAIXABANK",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "Large Cap",
    sector_name: "Financials",
    sub_industry_name: "Regional Banks",
    country_exposure_name: "Spain",
  },
  {
    instrument_id: 29,
    isin: "US15118V2079",
    name: "CELSIUS HOLDINGS INC",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Mid Cap",
    sector_name: "Consumer Staples",
    sub_industry_name: "Non-Alcoholic Beverages",
    country_exposure_name: "US",
  },
  {
    instrument_id: 30,
    isin: "US1912161007",
    name: "COCA-COLA COMPANY (THE) C",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Low",
    asset_class_level_name: "Stable",
    market_cap_name: "Mega Cap",
    sector_name: "Consumer Staples",
    sub_industry_name: "Non-Alcoholic Beverages",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 31,
    isin: "CA22717L1013",
    name: "CRONOS GROUP INC",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "High",
    asset_class_level_name: "Startup",
    market_cap_name: "Small Cap",
    sector_name: "Health Care",
    sub_industry_name: "Biotechnology",
    country_exposure_name: "North America",
  },
  {
    instrument_id: 32,
    isin: "ES0126775032",
    name: "DIA",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "Mid Cap",
    sector_name: "Consumer Staples",
    sub_industry_name: "Food Retail",
    country_exposure_name: "Spain",
  },
  {
    instrument_id: 33,
    isin: "US26441C2044",
    name: "DUKE ENERGY RG",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Low",
    asset_class_level_name: "Mature",
    market_cap_name: "Large Cap",
    sector_name: "Utilities",
    sub_industry_name: "Electric Utilities",
    country_exposure_name: "US",
  },
  {
    instrument_id: 34,
    isin: "US23355L1061",
    name: "DXC TECHNOLOGY CO",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mid Cap",
    sector_name: "Information Technology",
    sub_industry_name: "IT Consulting & Services",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 35,
    isin: "ES0130625512",
    name: "ENCE",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "Small Cap",
    sector_name: "Utilities",
    sub_industry_name: "Renewable Electricity",
    country_exposure_name: "Spain",
  },
  {
    instrument_id: 36,
    isin: "EUR.USD",
    name: "EUR.USD",
    instrument_type: "Currency Pair",
    profile_name: "Hedging",
    risk_level_name: "Moderate",
    asset_class_level_name: "N/A",
    market_cap_name: "N/A",
    sector_name: "FX",
    sub_industry_name: "Currency Pair",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 37,
    isin: "NL0015001FS8",
    name: "FERROVIAL SE",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Large Cap",
    sector_name: "Industrials",
    sub_industry_name: "Construction & Engineering",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 38,
    isin: "ES0171996087",
    name: "GRIFOLS",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mid Cap",
    sector_name: "Health Care",
    sub_industry_name: "Biotechnology",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 39,
    isin: "ES0148396007",
    name: "INDITEX",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Consumer Discretionary",
    sub_industry_name: "Apparel Retail",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 40,
    isin: "US45841N1072",
    name: "INTERACTIVE BROKERS GROUP",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "Large Cap",
    sector_name: "Financials",
    sub_industry_name: "Investment Banking & Brokerage",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 41,
    isin: "XS2940466316",
    name: "ISHARES BITCOIN TRUST",
    instrument_type: "Common Stock",
    profile_name: "Speculative",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Mega Cap",
    sector_name: "Financials",
    sub_industry_name: "Asset Management & Custody Banks",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 42,
    isin: "IE00B441G979",
    name: "ISHARES ETF MSCI WORLD - EUR HEDGED",
    instrument_type: "ETF",
    profile_name: "Hedging",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Equity ETF",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 43,
    isin: "IE00B1TXK627",
    name: "ISHARES GLOBAL WATER UCITS ETF",
    instrument_type: "ETF",
    profile_name: "Defensive",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Thematic Equity ETF",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 44,
    isin: "IE000ZOI8OK5",
    name: "ISHARES IBONDS DEC 2027 EUR CORPORATE",
    instrument_type: "ETF",
    profile_name: "Hedging",
    risk_level_name: "Low",
    asset_class_level_name: "Stable",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Bond ETF",
    country_exposure_name: "Europe",
  },
  {
    instrument_id: 45,
    isin: "IE000I8KRLL9",
    name: "ISHARES MSCI GLOBAL SEMICONDUCTOR",
    instrument_type: "ETF",
    profile_name: "Growth",
    risk_level_name: "High",
    asset_class_level_name: "Mature",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Thematic Equity ETF",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 46,
    isin: "IE00B53SZB19",
    name: "ISHARES NASDAQ 100 UCITS ETF U",
    instrument_type: "ETF",
    profile_name: "Hedging",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Equity ETF",
    country_exposure_name: "US",
  },
  {
    instrument_id: 47,
    isin: "IE00B3ZW0K18",
    name: "ISHARES S&P 500 MONTHLY",
    instrument_type: "ETF",
    profile_name: "Hedging",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Equity ETF",
    country_exposure_name: "US",
  },
  {
    instrument_id: 48,
    isin: "US4781601046",
    name: "JOHNSON&JOHNSON RG",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Low",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Health Care",
    sub_industry_name: "Pharmaceuticals",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 49,
    isin: "GB00BMHVL512",
    name: "KLARNA GROUP PLC",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Startup",
    market_cap_name: "Small Cap",
    sector_name: "Financials",
    sub_industry_name: "Capital Markets",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 50,
    isin: null,
    name: "LIBERBANK",
    instrument_type: "Common Stock",
    profile_name: null,
    risk_level_name: null,
    asset_class_level_name: null,
    market_cap_name: null,
    sector_name: null,
    sub_industry_name: null,
    country_exposure_name: null,
  },
  {
    instrument_id: 51,
    isin: "FR0000121014",
    name: "LOUIS VUITTON MOET HENNESSY",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Consumer Discretionary",
    sub_industry_name: "Luxury Goods",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 52,
    isin: "ES0105122024",
    name: "METROVACESA",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "Small Cap",
    sector_name: "Real Estate",
    sub_industry_name: "Real Estate Development",
    country_exposure_name: "Spain",
  },
  {
    instrument_id: 53,
    isin: "US5949181045",
    name: "MICROSOFT CORP",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Growth",
    market_cap_name: "Mega Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Systems Software",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 54,
    isin: "US5949724083",
    name: "MICROSTRATEGY INC.CLASS A",
    instrument_type: "Common Stock",
    profile_name: "Speculative",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Large Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Application Software",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 55,
    isin: "US61174X1090",
    name: "MONSTER BEVERAGE CORP",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Moderate",
    asset_class_level_name: "Growth",
    market_cap_name: "Large Cap",
    sector_name: "Consumer Staples",
    sub_industry_name: "Non-Alcoholic Beverages",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 56,
    isin: "US65339F1012",
    name: "NEXTERA ENERGY RG",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Low",
    asset_class_level_name: "Stable",
    market_cap_name: "Large Cap",
    sector_name: "Utilities",
    sub_industry_name: "Electric Utilities",
    country_exposure_name: "US",
  },
  {
    instrument_id: 57,
    isin: "US6703461052",
    name: "NUCOR CORP",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Large Cap",
    sector_name: "Materials",
    sub_industry_name: "Steel",
    country_exposure_name: "North America",
  },
  {
    instrument_id: 58,
    isin: "US67079K1007",
    name: "NUSCALE POWER CORP",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Growth",
    market_cap_name: "Mid Cap",
    sector_name: "Energy",
    sub_industry_name: "Advanced Nuclear Energy",
    country_exposure_name: "US",
  },
  {
    instrument_id: 59,
    isin: "US67066G1040",
    name: "NVIDIA CORPORATION",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Mega Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Semiconductors",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 60,
    isin: "ES0142090317",
    name: "OHL",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Small Cap",
    sector_name: "Industrials",
    sub_industry_name: "Construction & Engineering",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 61,
    isin: "US02156V1098",
    name: "OKLO INC. CLASS A COMMON",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Small Cap",
    sector_name: "Energy",
    sub_industry_name: "Advanced Nuclear Energy",
    country_exposure_name: "US",
  },
  {
    instrument_id: 62,
    isin: "US6792951054",
    name: "OKTA INC",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Growth",
    market_cap_name: "Large Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Application Software",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 63,
    isin: "US68389X1054",
    name: "ORACLE CORP",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Systems Software",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 64,
    isin: "US7170811035",
    name: "PFIZER RG",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Low",
    asset_class_level_name: "Mature",
    market_cap_name: "Large Cap",
    sector_name: "Health Care",
    sub_industry_name: "Pharmaceuticals",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 65,
    isin: "JE00B1VS3333",
    name: "PHAG",
    instrument_type: "ETC",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "N/A",
    sector_name: "Commodities",
    sub_industry_name: "Silver ETC",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 66,
    isin: "JE00B1VS3770",
    name: "PHAU",
    instrument_type: "ETC",
    profile_name: "Defensive",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "N/A",
    sector_name: "Commodities",
    sub_industry_name: "Gold ETC",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 67,
    isin: "JE00B1VS2W53",
    name: "PHPT",
    instrument_type: "ETC",
    profile_name: "Defensive",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "N/A",
    sector_name: "Commodities",
    sub_industry_name: "Platinum ETC",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 68,
    isin: "US6934831099",
    name: "POSCO ADR",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Large Cap",
    sector_name: "Materials",
    sub_industry_name: "Steel",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 69,
    isin: "US7427181091",
    name: "PROCTER&GAMBLE RG",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Low",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Consumer Staples",
    sub_industry_name: "Household Products",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 70,
    isin: "US74767V1098",
    name: "QUANTUMSCAPE CORP",
    instrument_type: "Common Stock",
    profile_name: "Speculative",
    risk_level_name: "High",
    asset_class_level_name: "Startup",
    market_cap_name: "Mid Cap",
    sector_name: "Industrials",
    sub_industry_name: "Electrical Equipment",
    country_exposure_name: "US",
  },
  {
    instrument_id: 71,
    isin: "US7561091049",
    name: "REALTY INM REIT RG",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Low",
    asset_class_level_name: "Stable",
    market_cap_name: "Large Cap",
    sector_name: "Real Estate",
    sub_industry_name: "Retail REITs",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 72,
    isin: "IT0003828271",
    name: "RECORDATI IND CHIM",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "Large Cap",
    sector_name: "Health Care",
    sub_industry_name: "Pharmaceuticals",
    country_exposure_name: "Europe",
  },
  {
    instrument_id: 73,
    isin: "ES0176252718",
    name: "SOL MELIA",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "Small Cap",
    sector_name: "Consumer Discretionary",
    sub_industry_name: "Lodging",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 74,
    isin: "ES0165386014",
    name: "SOLARIA",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mid Cap",
    sector_name: "Utilities",
    sub_industry_name: "Renewable Electricity",
    country_exposure_name: "Europe",
  },
  {
    instrument_id: 75,
    isin: "US8716071076",
    name: "SYSNOPSYS INC",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Large Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Systems Software",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 76,
    isin: "US8740391003",
    name: "TAIWAN SEMICONDUCTOR MANFT LTD ADR",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Semiconductors",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 77,
    isin: "US88160R1014",
    name: "TESLA INC",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Mega Cap",
    sector_name: "Consumer Discretionary",
    sub_industry_name: "Automobile Manufacturers",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 78,
    isin: "US8825081040",
    name: "TEXAS INSTRUMENT INC",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Large Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Semiconductors",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 79,
    isin: "US5007541064",
    name: "THE KRAFT HEINZ COMPANY",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "Large Cap",
    sector_name: "Consumer Staples",
    sub_industry_name: "Packaged Foods",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 80,
    isin: "ES0180907000",
    name: "UNICAJA",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mid Cap",
    sector_name: "Financials",
    sub_industry_name: "Regional Banks",
    country_exposure_name: "Spain",
  },
  {
    instrument_id: 81,
    isin: "USD.EUR",
    name: "USD.EUR",
    instrument_type: "Currency Pair",
    profile_name: "Hedging",
    risk_level_name: "Moderate",
    asset_class_level_name: "N/A",
    market_cap_name: "N/A",
    sector_name: "FX",
    sub_industry_name: "Currency Pair",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 82,
    isin: "IE00B3XXRP09",
    name: "VANGUARD ETF SP 500",
    instrument_type: "ETF",
    profile_name: "Hedging",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Equity ETF",
    country_exposure_name: "US",
  },
  {
    instrument_id: 83,
    isin: "IE00B9F5YL18",
    name: "VANGUARD FTSE ASIA PAC EX JP",
    instrument_type: "ETF",
    profile_name: "Hedging",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Equity ETF",
    country_exposure_name: "Asia",
  },
  {
    instrument_id: 84,
    isin: "IE00B945VV12",
    name: "VANGUARD FTSE DEVELOP EUROPE",
    instrument_type: "ETF",
    profile_name: "Hedging",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Equity ETF",
    country_exposure_name: "Europe",
  },
  {
    instrument_id: 85,
    isin: "IE00B3VVMM84",
    name: "VANGUARD FTSE EMERGING MARKETS",
    instrument_type: "ETF",
    profile_name: "Hedging",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Equity ETF",
    country_exposure_name: "Emerging Markets",
  },
  {
    instrument_id: 86,
    isin: "US92343V1044",
    name: "VERIZON COMM RG",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Low",
    asset_class_level_name: "Mature",
    market_cap_name: "Large Cap",
    sector_name: "Communication Services",
    sub_industry_name: "Integrated Telecommunication Services",
    country_exposure_name: "US",
  },
  {
    instrument_id: 87,
    isin: "US92537N1081",
    name: "VERTIV HOLDINGS CO",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Large Cap",
    sector_name: "Industrials",
    sub_industry_name: "Electrical Equipment",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 88,
    isin: "US92826C8394",
    name: "VISA INC.",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Low",
    asset_class_level_name: "Mature",
    market_cap_name: "Mega Cap",
    sector_name: "Industrials",
    sub_industry_name: "Data Processing & Outsourced Services",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 89,
    isin: "US92936U1097",
    name: "W.P. CAREY REIT RG",
    instrument_type: "Common Stock",
    profile_name: "Defensive",
    risk_level_name: "Low",
    asset_class_level_name: "Stable",
    market_cap_name: "Large Cap",
    sector_name: "Real Estate",
    sub_industry_name: "Diversified REITs",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 90,
    isin: "JE00B2QXZK10",
    name: "WISDOMTREE COCOA ETC",
    instrument_type: "ETC",
    profile_name: "Defensive",
    risk_level_name: "Moderate",
    asset_class_level_name: "N/A",
    market_cap_name: "N/A",
    sector_name: "Commodities",
    sub_industry_name: "Agricultural Commodity ETC",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 91,
    isin: "IE00BLRPRL42",
    name: "WISDOMTREE NASDAQ 100 3X DAILY LEVERAGED",
    instrument_type: "ETF",
    profile_name: "Speculative",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Equity ETF",
    country_exposure_name: "US",
  },
  {
    instrument_id: 92,
    isin: "JE00B8DFY052",
    name: "WISDOMTREE PHYSICAL GOLD - EUR (HEDGED)",
    instrument_type: "ETC",
    profile_name: "Defensive",
    risk_level_name: "Moderate",
    asset_class_level_name: "Stable",
    market_cap_name: "N/A",
    sector_name: "Commodities",
    sub_industry_name: "Gold Hedged ETC",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 93,
    isin: "IE00B7Y34M31",
    name: "WISDOMTREE S&P 500 3X DAILY LEVERAGED",
    instrument_type: "ETF",
    profile_name: "Speculative",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Equity ETF",
    country_exposure_name: "US",
  },
  {
    instrument_id: 94,
    isin: "IE0003BJ2JS4",
    name: "WISDOMTREE URANIUM AND NUCLEAR ENERGY",
    instrument_type: "ETF",
    profile_name: "Speculative",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "N/A",
    sector_name: "ETFs",
    sub_industry_name: "Thematic Equity ETF",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 95,
    isin: "JE00BN574F90",
    name: "WIZZ AIR HOLDINGS PLC-WI",
    instrument_type: "Common Stock",
    profile_name: "Cyclical",
    risk_level_name: "Moderate",
    asset_class_level_name: "Mature",
    market_cap_name: "Mid Cap",
    sector_name: "Industrials",
    sub_industry_name: "Airlines",
    country_exposure_name: "Europe",
  },
  {
    instrument_id: 96,
    isin: "US98980G1022",
    name: "ZSCALER RG",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Large Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Application Software",
    country_exposure_name: "Global",
  },
  {
    instrument_id: 97,
    isin: "US8269191024",
    name: "SILICON LABORATORIES INC",
    instrument_type: "Common Stock",
    profile_name: "Growth",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Mid Cap",
    sector_name: "Information Technology",
    sub_industry_name: "Semiconductors",
    country_exposure_name: "US",
  },
  {
    instrument_id: 98,
    isin: "US44916E1001",
    name: "IPERIONX LTD",
    instrument_type: "Common Stock",
    profile_name: "Speculative",
    risk_level_name: "High",
    asset_class_level_name: "Growth",
    market_cap_name: "Small Cap",
    sector_name: "Materials",
    sub_industry_name: "Diversified Metals & Mining",
    country_exposure_name: "US",
  },
];
