/**
 * Instrument Master Data
 *
 * Instruments represent the underlying assets (Companies, KPIs, Cryptocurrencies, etc.).
 * This seed data provides a set of common instruments.
 *
 * Generated from tmp/symbol_source.txt
 */

export interface InstrumentData {
  instrument_id: number;
  isin: string;
  name: string;
  instrument_type: string;
}

export const instruments: InstrumentData[] = [
  {
    instrument_id: 1,
    isin: "ES0132105018",
    name: "Acerinox SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 2,
    isin: "US0079031078",
    name: "Advanced Micro Devices Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 3,
    isin: "ES0152768612",
    name: "Airtificial Intelligence Structures SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 4,
    isin: "US02079K3059",
    name: "Alphabet Inc Class A",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 5,
    isin: "US02079K1079",
    name: "Alphabet Inc Class C",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 6,
    isin: "ES0109067019",
    name: "Amadeus It Group SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 7,
    isin: "US0231351067",
    name: "Amazon.com Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 8,
    isin: "US02376R1023",
    name: "American Airlines Group Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 9,
    isin: "ES0109260531",
    name: "Amper SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 10,
    isin: "LU1681038243",
    name: "AMUNDI NASDAQ 100-EUR",
    instrument_type: "ETF",
  },
  {
    instrument_id: 11,
    isin: "US0378331005",
    name: "Apple Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 12,
    isin: "US03938L2034",
    name: "ArcelorMittal SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 13,
    isin: "LU1598757687",
    name: "ArcelorMittal SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 14,
    isin: "GB0000595859",
    name: "Arm Holdings PLC - ADR",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 15,
    isin: "NL0010273215",
    name: "ASML Holding NV",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 16,
    isin: "USN070592100",
    name: "ASML Holding NV",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 17,
    isin: "US00206R1023",
    name: "AT&T Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 18,
    isin: "GB00BZ09BD16",
    name: "Atlassian Corp",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 19,
    isin: "ES0105216005",
    name: "Audax Renovables SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 20,
    isin: "US0605051046",
    name: "Bank of America Corp",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 21,
    isin: "CA0679011084",
    name: "Barrick Mining Corp",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 22,
    isin: "AU000000BKY0",
    name: "Berkeley Energia Ltd",
    instrument_type: "ETC",
  },
  {
    instrument_id: 23,
    isin: "US11135F1012",
    name: "Broadcom Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 24,
    isin: "ES0140609019",
    name: "CaixaBank SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 25,
    isin: "US15118V2079",
    name: "Celsius Holdings Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 26,
    isin: "US1912161007",
    name: "Coca-Cola Co",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 27,
    isin: "CA22717L1013",
    name: "Cronos Group Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 28,
    isin: "ES0126775032",
    name: "Distribuidora Internacnl de Alimntacn SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 29,
    isin: "US26441C2044",
    name: "Duke Energy Corp",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 30,
    isin: "US23355L1061",
    name: "DXC Technology Co",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 31,
    isin: "ES0130625512",
    name: "ENCE Energia y Celulosa SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 32,
    isin: "EUR.USD",
    name: "EUR/USD",
    instrument_type: "Currency Pair",
  },
  {
    instrument_id: 33,
    isin: "NL0015001FS8",
    name: "Ferrovial SE",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 34,
    isin: "ES0171996087",
    name: "Grifols SA Class A",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 35,
    isin: "ES0148396007",
    name: "Industria de Diseno Textil SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 36,
    isin: "US45841N1072",
    name: "Interactive Brokers Group, Inc.",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 37,
    isin: "XS2940466316",
    name: "iShares Open End Bitcoin ETP",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 38,
    isin: "IE00B441G979",
    name: "iShares MSCI World EUR Hedged UCITS ETF (Acc)",
    instrument_type: "ETF",
  },
  {
    instrument_id: 39,
    isin: "IE00B1TXK627",
    name: "iShares Global Water UCITS ETF USD (Dist)",
    instrument_type: "ETF",
  },
  {
    instrument_id: 40,
    isin: "IE000ZOI8OK5",
    name: "iShares iBond Dec 2027 Term   Corp UCITS ETF EUR A",
    instrument_type: "ETF",
  },
  {
    instrument_id: 41,
    isin: "IE000I8KRLL9",
    name: "iShares MSCI Global Semiconductors UCITS ETF USD A",
    instrument_type: "ETF",
  },
  {
    instrument_id: 42,
    isin: "IE00B53SZB19",
    name: "ISHARES NASDAQ 100 UCITS ETF U",
    instrument_type: "ETF",
  },
  {
    instrument_id: 43,
    isin: "IE00B3ZW0K18",
    name: "iShares S&P 500 EUR Hedged UCITS ETF (Acc)",
    instrument_type: "ETF",
  },
  {
    instrument_id: 44,
    isin: "US4781601046",
    name: "Johnson & Johnson",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 45,
    isin: "GB00BMHVL512",
    name: "Klarna Group PLC",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 46,
    isin: "FR0000121014",
    name: "LVMH Moet Hennessy Louis Vuitton SE",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 47,
    isin: "ES0105122024",
    name: "Metrovacesa SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 48,
    isin: "US98980G1022",
    name: "Microsoft Corp",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 49,
    isin: "US5949724083",
    name: "Strategy Inc Class A",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 50,
    isin: "US61174X1090",
    name: "Monster Beverage Corp",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 51,
    isin: "US65339F1012",
    name: "NextEra Energy Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 52,
    isin: "US6703461052",
    name: "Nucor Corp",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 53,
    isin: "US67079K1007",
    name: "Nuscale Power Corp",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 54,
    isin: "US67066G1040",
    name: "NVIDIA Corp",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 55,
    isin: "ES0142090317",
    name: "Obrascon Huarte Lain SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 56,
    isin: "US02156V1098",
    name: "Oklo Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 57,
    isin: "US6792951054",
    name: "Okta Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 58,
    isin: "US7170811035",
    name: "Pfizer Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 59,
    isin: "JE00B1VS3333",
    name: "WisdomTree Physical Silver Individual Securities ETC",
    instrument_type: "ETC",
  },
  {
    instrument_id: 60,
    isin: "JE00B1VS3770",
    name: "WisdomTree Physical Gold Individual Securities ETC",
    instrument_type: "ETC",
  },
  {
    instrument_id: 61,
    isin: "JE00B1VS2W53",
    name: "WisdomTree Physical Platinum ETC",
    instrument_type: "ETC",
  },
  {
    instrument_id: 62,
    isin: "US6934831099",
    name: "Posco Holdings Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 63,
    isin: "US7427181091",
    name: "Procter & Gamble Co",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 64,
    isin: "US74767V1098",
    name: "Quantumscape Corp",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 65,
    isin: "US7561091049",
    name: "Realty Income Corp",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 66,
    isin: "IT0003828271",
    name: "Recordati Industria Chmc Frmctc SpA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 67,
    isin: "ES0176252718",
    name: "Melia Hotels International SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 68,
    isin: "ES0165386014",
    name: "Solaria Energia y Medio Ambiente SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 69,
    isin: "US8716071076",
    name: "Synopsys Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 70,
    isin: "US8740391003",
    name: "Taiwan Semicndctr Mnufctrng Co Ltd",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 71,
    isin: "US88160R1014",
    name: "Tesla Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 72,
    isin: "US8825081040",
    name: "Texas Instruments Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 73,
    isin: "US5007541064",
    name: "Kraft Heinz Co",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 74,
    isin: "ES0180907000",
    name: "Unicaja Banco SA",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 75,
    isin: "USD.EUR",
    name: "USD/EUR",
    instrument_type: "Currency Pair",
  },
  {
    instrument_id: 76,
    isin: "IE00B3XXRP09",
    name: "Vanguard S&P 500 UCITS ETF USD Dis",
    instrument_type: "ETF",
  },
  {
    instrument_id: 77,
    isin: "IE00B9F5YL18",
    name: "Vanguard FTSEDvlpAsiaPacexJpn UCITS ETF USDDis",
    instrument_type: "ETF",
  },
  {
    instrument_id: 78,
    isin: "IE00B945VV12",
    name: "Vanguard FTSE Developed Europe UCITS ETF EUR D",
    instrument_type: "ETF",
  },
  {
    instrument_id: 79,
    isin: "IE00B3VVMM84",
    name: "Vanguard FTSE Emerging Mkts UCITS ETF USD Dis",
    instrument_type: "ETF",
  },
  {
    instrument_id: 80,
    isin: "US92343V1044",
    name: "Verizon Communications Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 81,
    isin: "US92537N1081",
    name: "Vertiv Holdings Co",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 82,
    isin: "US92826C8394",
    name: "Visa Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 83,
    isin: "US92936U1097",
    name: "WP Carey Inc",
    instrument_type: "Common Stock",
  },
  {
    instrument_id: 84,
    isin: "JE00B2QXZK10",
    name: "WISDOMTREE COCOA ETC",
    instrument_type: "ETC",
  },
  {
    instrument_id: 85,
    isin: "IE00BLRPRL42",
    name: "Wisdomtree Nasdaq 100 3X Daily Leveraged",
    instrument_type: "ETF",
  },
  {
    instrument_id: 86,
    isin: "JE00B8DFY052",
    name: "ETFS EUR Daily Hedged Physical Gold ETC",
    instrument_type: "ETC",
  },
  {
    instrument_id: 87,
    isin: "IE00B7Y34M31",
    name: "Wisdomtree S&P 500 3X Daily Leveraged",
    instrument_type: "ETF",
  },
  {
    instrument_id: 88,
    isin: "IE0003BJ2JS4",
    name: "WisdomTree Uranium and Nuclear Energy UCITS - USD Acc ETF",
    instrument_type: "ETF",
  },
  {
    instrument_id: 89,
    isin: "JE00BN574F90",
    name: "Wizz Air Holdings PLC",
    instrument_type: "Common Stock",
  },
];
