/**
 * Listing Master Data
 *
 * Listings represent the trading connection between an Instrument and a Market.
 *
 * Generated from tmp/symbol_source.txt
 */

export interface ListingData {
  market_prefix: string; // Used to resolve market_id
  symbol_code: string;
  display_ticker: string;
  isin: string; // Used to resolve instrument_id
  currency_code: string; // Used to resolve currency_id
}

export const listings: ListingData[] = [
  {
    market_prefix: "VIE",
    symbol_code: "ACX",
    display_ticker: "VIE:ACX",
    isin: "ES0132105018",
    currency_code: "EUR",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "AMD",
    display_ticker: "NASDAQ:AMD",
    isin: "US0079031078",
    currency_code: "USD",
  },
  {
    market_prefix: "BME",
    symbol_code: "AI",
    display_ticker: "BME:AI",
    isin: "ES0152768612",
    currency_code: "EUR",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "GOOGL",
    display_ticker: "NASDAQ:GOOGL",
    isin: "US02079K3059",
    currency_code: "USD",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "GOOG",
    display_ticker: "NASDAQ:GOOG",
    isin: "US02079K1079",
    currency_code: "USD",
  },
  {
    market_prefix: "BME",
    symbol_code: "AMS",
    display_ticker: "BME:AMS",
    isin: "ES0109067019",
    currency_code: "EUR",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "AMZN",
    display_ticker: "NASDAQ:AMZN",
    isin: "US0231351067",
    currency_code: "USD",
  },
  {
    market_prefix: "FRA",
    symbol_code: "AMD",
    display_ticker: "FRA:AMD",
    isin: "US0079031078",
    currency_code: "EUR",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "AAL",
    display_ticker: "NASDAQ:AAL",
    isin: "US02376R1023",
    currency_code: "USD",
  },
  {
    market_prefix: "BME",
    symbol_code: "AMP",
    display_ticker: "BME:AMP",
    isin: "ES0109260531",
    currency_code: "EUR",
  },
  {
    market_prefix: "EPA",
    symbol_code: "ANX-ETFP",
    display_ticker: "EPA:ANX-ETFP",
    isin: "LU1681038243",
    currency_code: "EUR",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "AAPL",
    display_ticker: "NASDAQ:AAPL",
    isin: "US0378331005",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "MT",
    display_ticker: "NYSE:MT",
    isin: "US03938L2034",
    currency_code: "USD",
  },
  {
    market_prefix: "BME",
    symbol_code: "MTS",
    display_ticker: "BME:MTS",
    isin: "LU1598757687",
    currency_code: "EUR",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "ARM",
    display_ticker: "NASDAQ:ARM",
    isin: "GB0000595859",
    currency_code: "USD",
  },
  {
    market_prefix: "AMS",
    symbol_code: "ASML",
    display_ticker: "AMS:ASML",
    isin: "NL0010273215",
    currency_code: "EUR",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "ASML",
    display_ticker: "NASDAQ:ASML",
    isin: "USN070592100",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "T",
    display_ticker: "NYSE:T",
    isin: "US00206R1023",
    currency_code: "USD",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "TEAM",
    display_ticker: "NASDAQ:TEAM",
    isin: "GB00BZ09BD16",
    currency_code: "USD",
  },
  {
    market_prefix: "BME",
    symbol_code: "ADX",
    display_ticker: "BME:ADX",
    isin: "ES0105216005",
    currency_code: "EUR",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "BAC",
    display_ticker: "NYSE:BAC",
    isin: "US0605051046",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "B",
    display_ticker: "NYSE:B",
    isin: "CA0679011084",
    currency_code: "USD",
  },
  {
    market_prefix: "BME",
    symbol_code: "BKY",
    display_ticker: "BME:BKY",
    isin: "AU000000BKY0",
    currency_code: "EUR",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "AVGO",
    display_ticker: "NASDAQ:AVGO",
    isin: "US11135F1012",
    currency_code: "USD",
  },
  {
    market_prefix: "BME",
    symbol_code: "CABK",
    display_ticker: "BME:CABK",
    isin: "ES0140609019",
    currency_code: "EUR",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "CELH",
    display_ticker: "NASDAQ:CELH",
    isin: "US15118V2079",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "KO",
    display_ticker: "NYSE:KO",
    isin: "US1912161007",
    currency_code: "USD",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "CRON",
    display_ticker: "NASDAQ:CRON",
    isin: "CA22717L1013",
    currency_code: "USD",
  },
  {
    market_prefix: "BME",
    symbol_code: "DIA",
    display_ticker: "BME:DIA",
    isin: "ES0126775032",
    currency_code: "EUR",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "DUK",
    display_ticker: "NYSE:DUK",
    isin: "US26441C2044",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "DXC",
    display_ticker: "NYSE:DXC",
    isin: "US23355L1061",
    currency_code: "USD",
  },
  {
    market_prefix: "BME",
    symbol_code: "ENC",
    display_ticker: "BME:ENC",
    isin: "ES0130625512",
    currency_code: "EUR",
  },
  {
    market_prefix: "CURRENCY",
    symbol_code: "EURUSD",
    display_ticker: "CURRENCY:EURUSD",
    isin: "EUR.USD",
    currency_code: "EUR",
  },
  {
    market_prefix: "BME",
    symbol_code: "FER",
    display_ticker: "BME:FER",
    isin: "NL0015001FS8",
    currency_code: "EUR",
  },
  {
    market_prefix: "BME",
    symbol_code: "GRF",
    display_ticker: "BME:GRF",
    isin: "ES0171996087",
    currency_code: "EUR",
  },
  {
    market_prefix: "BME",
    symbol_code: "ITX",
    display_ticker: "BME:ITX",
    isin: "ES0148396007",
    currency_code: "EUR",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "IBKR",
    display_ticker: "NASDAQ:IBKR",
    isin: "US45841N1072",
    currency_code: "USD",
  },
  {
    market_prefix: "SWX",
    symbol_code: "IB1T",
    display_ticker: "SWX:IB1T",
    isin: "XS2940466316",
    currency_code: "EUR",
  },
  {
    market_prefix: "BIT",
    symbol_code: "IWDE",
    display_ticker: "BIT:IWDE",
    isin: "IE00B441G979",
    currency_code: "EUR",
  },
  {
    market_prefix: "LON",
    symbol_code: "IH2O",
    display_ticker: "LON:IH2O",
    isin: "IE00B1TXK627",
    currency_code: "EUR",
  },
  {
    market_prefix: "EPA",
    symbol_code: "IB27",
    display_ticker: "EPA:IB27",
    isin: "IE000ZOI8OK5",
    currency_code: "EUR",
  },
  {
    market_prefix: "LON",
    symbol_code: "SEMI",
    display_ticker: "LON:SEMI",
    isin: "IE000I8KRLL9",
    currency_code: "EUR",
  },
  {
    market_prefix: "BIT",
    symbol_code: "CSNDX",
    display_ticker: "BIT:CSNDX",
    isin: "IE00B53SZB19",
    currency_code: "EUR",
  },
  {
    market_prefix: "LON",
    symbol_code: "IUSE",
    display_ticker: "LON:IUSE",
    isin: "IE00B3ZW0K18",
    currency_code: "EUR",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "JNJ",
    display_ticker: "NYSE:JNJ",
    isin: "US4781601046",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "KLAR",
    display_ticker: "NYSE:KLAR",
    isin: "GB00BMHVL512",
    currency_code: "USD",
  },
  {
    market_prefix: "EPA",
    symbol_code: "MC",
    display_ticker: "EPA:MC",
    isin: "FR0000121014",
    currency_code: "EUR",
  },
  {
    market_prefix: "BME",
    symbol_code: "MVC",
    display_ticker: "BME:MVC",
    isin: "ES0105122024",
    currency_code: "EUR",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "MSFT",
    display_ticker: "NASDAQ:MSFT",
    isin: "US98980G1022",
    currency_code: "USD",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "MSTR",
    display_ticker: "NASDAQ:MSTR",
    isin: "US5949724083",
    currency_code: "USD",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "MNST",
    display_ticker: "NASDAQ:MNST",
    isin: "US61174X1090",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "NEE",
    display_ticker: "NYSE:NEE",
    isin: "US65339F1012",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "NUE",
    display_ticker: "NYSE:NUE",
    isin: "US6703461052",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "SMR",
    display_ticker: "NYSE:SMR",
    isin: "US67079K1007",
    currency_code: "USD",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "NVDA",
    display_ticker: "NASDAQ:NVDA",
    isin: "US67066G1040",
    currency_code: "USD",
  },
  {
    market_prefix: "BME",
    symbol_code: "OHLA",
    display_ticker: "BME:OHLA",
    isin: "ES0142090317",
    currency_code: "EUR",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "OKLO",
    display_ticker: "NYSE:OKLO",
    isin: "US02156V1098",
    currency_code: "USD",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "OKTA",
    display_ticker: "NASDAQ:OKTA",
    isin: "US6792951054",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "ORCL",
    display_ticker: "NYSE:ORCL",
    isin: "US98980G1022",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "PFE",
    display_ticker: "NYSE:PFE",
    isin: "US7170811035",
    currency_code: "USD",
  },
  {
    market_prefix: "BIT",
    symbol_code: "PHAG",
    display_ticker: "BIT:PHAG",
    isin: "JE00B1VS3333",
    currency_code: "EUR",
  },
  {
    market_prefix: "BIT",
    symbol_code: "PHAU",
    display_ticker: "BIT:PHAU",
    isin: "JE00B1VS3770",
    currency_code: "EUR",
  },
  {
    market_prefix: "BIT",
    symbol_code: "PHPT",
    display_ticker: "BIT:PHPT",
    isin: "JE00B1VS2W53",
    currency_code: "EUR",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "PKX",
    display_ticker: "NYSE:PKX",
    isin: "US6934831099",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "PG",
    display_ticker: "NYSE:PG",
    isin: "US7427181091",
    currency_code: "USD",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "QS",
    display_ticker: "NASDAQ:QS",
    isin: "US74767V1098",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "O",
    display_ticker: "NYSE:O",
    isin: "US7561091049",
    currency_code: "USD",
  },
  {
    market_prefix: "BIT",
    symbol_code: "REC",
    display_ticker: "BIT:REC",
    isin: "IT0003828271",
    currency_code: "EUR",
  },
  {
    market_prefix: "BME",
    symbol_code: "MEL",
    display_ticker: "BME:MEL",
    isin: "ES0176252718",
    currency_code: "EUR",
  },
  {
    market_prefix: "BME",
    symbol_code: "SLR",
    display_ticker: "BME:SLR",
    isin: "ES0165386014",
    currency_code: "EUR",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "SNPS",
    display_ticker: "NASDAQ:SNPS",
    isin: "US8716071076",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "TSM",
    display_ticker: "NYSE:TSM",
    isin: "US8740391003",
    currency_code: "USD",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "TSLA",
    display_ticker: "NASDAQ:TSLA",
    isin: "US88160R1014",
    currency_code: "USD",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "TXN",
    display_ticker: "NASDAQ:TXN",
    isin: "US8825081040",
    currency_code: "USD",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "KHC",
    display_ticker: "NASDAQ:KHC",
    isin: "US5007541064",
    currency_code: "USD",
  },
  {
    market_prefix: "BME",
    symbol_code: "UNI",
    display_ticker: "BME:UNI",
    isin: "ES0180907000",
    currency_code: "EUR",
  },
  {
    market_prefix: "CURRENCY",
    symbol_code: "USDEUR",
    display_ticker: "CURRENCY:USDEUR",
    isin: "USD.EUR",
    currency_code: "USD",
  },
  {
    market_prefix: "BIT",
    symbol_code: "VUSA",
    display_ticker: "BIT:VUSA",
    isin: "IE00B3XXRP09",
    currency_code: "EUR",
  },
  {
    market_prefix: "BIT",
    symbol_code: "VAPX",
    display_ticker: "BIT:VAPX",
    isin: "IE00B9F5YL18",
    currency_code: "EUR",
  },
  {
    market_prefix: "BIT",
    symbol_code: "VEUR",
    display_ticker: "BIT:VEUR",
    isin: "IE00B945VV12",
    currency_code: "EUR",
  },
  {
    market_prefix: "BIT",
    symbol_code: "VFEM",
    display_ticker: "BIT:VFEM",
    isin: "IE00B3VVMM84",
    currency_code: "EUR",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "VZ",
    display_ticker: "NYSE:VZ",
    isin: "US92343V1044",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "VRT",
    display_ticker: "NYSE:VRT",
    isin: "US92537N1081",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "V",
    display_ticker: "NYSE:V",
    isin: "US92826C8394",
    currency_code: "USD",
  },
  {
    market_prefix: "NYSE",
    symbol_code: "WPC",
    display_ticker: "NYSE:WPC",
    isin: "US92936U1097",
    currency_code: "USD",
  },
  {
    market_prefix: "LON",
    symbol_code: "COCO",
    display_ticker: "LON:COCO",
    isin: "JE00B2QXZK10",
    currency_code: "EUR",
  },
  {
    market_prefix: "BIT",
    symbol_code: "QQQ3",
    display_ticker: "BIT:QQQ3",
    isin: "IE00BLRPRL42",
    currency_code: "EUR",
  },
  {
    market_prefix: "BIT",
    symbol_code: "GBSE",
    display_ticker: "BIT:GBSE",
    isin: "JE00B8DFY052",
    currency_code: "EUR",
  },
  {
    market_prefix: "BIT",
    symbol_code: "3USL",
    display_ticker: "BIT:3USL",
    isin: "IE00B7Y34M31",
    currency_code: "EUR",
  },
  {
    market_prefix: "LON",
    symbol_code: "NCLR",
    display_ticker: "LON:NCLR",
    isin: "IE0003BJ2JS4",
    currency_code: "USD",
  },
  {
    market_prefix: "LON",
    symbol_code: "WIZZ",
    display_ticker: "LON:WIZZ",
    isin: "JE00BN574F90",
    currency_code: "GBP",
  },
  {
    market_prefix: "NASDAQ",
    symbol_code: "ZS",
    display_ticker: "NASDAQ:ZS",
    isin: "US98980G1022",
    currency_code: "USD",
  },
];
